name: Release

on:
  push:
    tags: [ 'v*.*.*' ]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Temurin JDK 17 with OSSRH + GPG
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: GPG_PASSPHRASE

      - name: Derive version from tag (v0.1.0 -> 0.1.0)
        id: v
        run: echo "VER=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Set project version
        run: mvn -B -ntp versions:set -DnewVersion=${{ steps.v.outputs.VER }} -DgenerateBackupPoms=false

      - name: Release to Maven Central
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
        run: mvn -B -ntp -P ossrh-sign clean deploy nexus-staging:release
